name: Release

on:
    workflow_dispatch:
        inputs:
            version:
                type: string
                description: Full version number to be release (example: 0.1.0)
                required: true
            tag:
                type: boolean
                description: Create a git tag for this release?
                default: true
                
        #    dry-run:
        #        description: 'Dry run the release?'
        #        required: false
        #        default: true
run-name: "Release: ${{ inputs.version }}"

jobs:
    create-release:
        env:
            INTERNAL_REPO_URL: ${{ secrets.INTERNAL_REPO_URL }}
            INTERNAL_REPO_USERNAME: ${{ secrets.INTERNAL_REPO_USERNAME }}
            INTERNAL_REPO_PASSWORD: ${{ secrets.INTERNAL_REPO_PASSWORD }}
            JDK_VERSION: '17'
        
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source
              uses: actions/checkout@v4
              with:
                  clean: true
            
            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                  java-version: ${{ env.JDK_VERSION }}
                  distribution: 'temurin'
                  cache: maven

            - name: Create Maven settings.xml
              run: |
                mkdir -p ~/.m2
                cat > ~/.m2/settings.xml <<EOF
                <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
                    <servers>
                        <server>
                            <id>internal-repo</id>
                            <username>${INTERNAL_REPO_USERNAME}</username>
                            <password>${INTERNAL_REPO_PASSWORD}</password>
                        </server>
                    </servers>
                    <profiles>
                        <profile>
                            <id>internal</id>
                            <activation>
                                <activeByDefault>true</activeByDefault>
                            </activation>
                            <repositories>
                                <repository>
                                    <id>internal-repo</id>
                                    <url>${INTERNAL_REPO_URL}</url>
                                </repository>
                            </repositories>
                            <pluginRepositories>
                                <pluginRepository>
                                    <id>internal-repo</id>
                                    <url>${INTERNAL_REPO_URL}</url>
                                </pluginRepository>
                            </pluginRepositories>
                        </profile>
                    </profiles>
                </settings>
                EOF
                
            - name: Deploy
              run: mvn clean deploy -s ~/.m2/settings.xml

            - name: Tag and Push
              if: inputs.tag
              run: |
                git tag releases/${{ inputs.version }} HEAD
                git push origin releases/${{ inputs.version }}
            
            #- name: Build with Maven
            #  run: mvn clean -B package --file pom.xml

            #- name: Simulate Release
            #  if: ${{ github.event.inputs.dry-run == 'true' }}
            #  run: echo "Dry run enabled - skipping tag, version bump, and deploy."

            #- name: Create Release
            #  if: ${{ github.event.inputs.dry-run != 'true' }}
            #  run: echo "Creating release."
